---
# This file performs basic assumptions checks

- name: "Require Correct Linux Distribution"
  assert:
    that: ansible_distribution | lower in ['redhat', 'centos']
    msg:  "This Linux distrution is not supported by the role."

- name: "Require Supported RDBMS"
  assert:
    that: ripple_solution_db_dialect in ['postgres']
    msg:  "This role supports only 'postgres' RDBMS for Ripple Solution."

- name: "Required FX Connector Pairs"
  assert:
    that: not fx_connector_enabled | default(False) or
          fx_connector_pairs | default([]) | length > 0
    msg: "The list \"fx_connector_pairs\" should NOT have less than 1 items"
