---
# This file takes care of installing the configuration files

#
# Read Keys and Fingerprints
#

- name: "Read Ripple Connect Secrets"
  no_log: true
  shell: "cat {{ pia_path }}/{{ item }}.pia"
  register: ripple_connect_secrets
  changed_when: false
  with_items:
   - mac_key
   - external_access_token_key
   - client_access_token_key
   - ilp_key

- name: "Read FX Connector Secrets"
  no_log: true
  shell: "cat {{ pia_path }}/{{ item }}.pia"
  register: connector_secrets
  changed_when: false
  with_items:
   - CONNECTOR_QUOTE_HMAC_KEY
  when: fx_connector_info.enabled

- set_fact:
    connector_quote_hmac_key: "{{ connector_secrets.results[0].stdout.split(' ')[2] }}"
  when: fx_connector_info.enabled

- name: "Read ILP Validator Secrets"
  no_log: true
  shell: "cat {{ pia_path }}/validator_key_pair.pia"
  changed_when: false
  register: validator_key
  when: ilp_validator_info.enabled

- set_fact:
    validator_ed25519_secret_key: "{{ validator_key.stdout_lines[1].split(' ')[2] }}"
    validator_ed25519_public_key: "{{ validator_key.stdout_lines[0].split(' ')[2] }}"
  when: ilp_validator_info.enabled

- name: "Read Fingerprints"
  no_log: "{{ ripple_solution_no_log | default(True) | bool }}"
  shell: "cat {{ cert_path }}/{{ item.crt_prefix }}.fpt"
  changed_when: false
  when: item.enabled
  with_items:
   - "{{ cert_items }}"
  register: fingerprints


#
# Configuration files
#

- set_fact:
    client_credentials:
      operator:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'operator') | list }}"
        hashes: "{{ hashed_operator_passwords }}"
      monitor:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'monitor') | list }}"
        hashes: "{{ hashed_monitor_passwords }}"
      partner:
        users:  "{{ ripple_connect_partners | sum(attribute='partner_users', start=[]) | list }}"
        hashes: "{{ hashed_partner_passwords }}"
      custom_rate_operator:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'custom_rate_operator') | list }}"
        hashes: "{{ hashed_custom_rate_operator_passwords }}"

- name: "Clean Examples"
  shell: "rm -f {{ ripple_solution_config_base }}/*example*"
  changed_when: false

- name: "Install Configuration Files"
  template:
    src:    "ripple-solution/{{ item }}.j2"
    dest:   "{{ ripple_solution_config_base }}/{{ item }}"
    mode:   '0644'
    force:  yes
    owner:  "{{ ripple_solution_user }}"
    group:  "{{ ripple_solution_group }}"
    seuser: system_u
    serole: object_r
    setype: usr_t
  register: config_files_status
  with_items:
   - config-ilp.json
   - config.json
   - database.json
   - entities.json
   - secrets.json
   - server.json
