---

#
# Passwords encryption
#

- name: "Read Existing Secrets"
  command: cat {{ ripple_solution_config_base }}/secrets.json
  register: existing_secrets_tmp
  ignore_errors: yes

- set_fact:
    existing_secrets: "{{ existing_secrets_tmp.stdout | from_json }}"

- name: "Encrypt Known Remotes Passwords"
  shell: node /opt/ripple-solution/scripts/encrypt_string.js {{ admin_key }} <<< '{{ item.password }}'
  changed_when: false
  register: encrypted_known_remote_passwords
  with_items:
   - "{{ ripple_connect_partners }}"

- name: "Encrypt Database Passwords"
  shell: node /opt/ripple-solution/scripts/encrypt_string.js {{ admin_key }} <<< '{{ ripple_connect_db_pass }}'
  changed_when: false
  register: encrypted_database_password

- name: "Encrypt RabbiMQ Passwords"
  shell: node /opt/ripple-solution/scripts/encrypt_string.js {{ admin_key }} <<< '{{ ripple_connect_rabbitmq.mq_password }}'
  changed_when: false
  when: ripple_connect_rabbitmq | default({})
  register: encrypted_rabbitmq_password

#
# Passwords hashing
#

- name: "Hash Operator Passwords"
  shell: node /opt/ripple-solution/scripts/hash_password.js <<< '{{ item.username }}:RippleSolution:{{ item.password }}'
  changed_when: false
  register: hashed_operator_passwords
  with_items:
   - "{{ ripple_connect_users | selectattr('type', 'equalto', 'operator') | list }}"

- name: "Hash Monitor Passwords"
  shell: node /opt/ripple-solution/scripts/hash_password.js <<< '{{ item.username }}:RippleSolution:{{ item.password }}'
  changed_when: false
  register: hashed_monitor_passwords
  with_items:
   - "{{ ripple_connect_users | selectattr('type', 'equalto', 'monitor') | list }}"

- name: "Hash Custom Rate Operator Passwords"
  shell: node /opt/ripple-solution/scripts/hash_password.js <<< '{{ item.username }}:RippleSolution:{{ item.password }}'
  changed_when: false
  register: hashed_custom_rate_operator_passwords
  with_items:
   - "{{ ripple_connect_users | selectattr('type', 'equalto', 'custom_rate_operator') | list }}"

- name: "Hash Partner Passwords"
  shell: node /opt/ripple-solution/scripts/hash_password.js <<< '{{ item.username }}:RippleSolution:{{ item.password }}'
  changed_when: false
  register: hashed_partner_passwords
  with_items:
   - "{{ ripple_connect_partners | sum(attribute='partner_users', start=[]) | list }}"

#
# Read Key Pairs and Fingerprints
#

- name: "Read Ripple Connect Secrets"
  shell: "cat {{ pia_path }}/{{ item }}.pia"
  register: ripple_connect_secrets
  changed_when: false
  with_items:
   - mac_key
   - external_access_token_key
   - client_access_token_key
   - ilp_key

- name: "Read Connector Secrets"
  shell: "cat {{ pia_path }}/{{ item }}.pia"
  register: connector_secrets
  changed_when: false
  with_items:
   - CONNECTOR_QUOTE_HMAC_KEY
  when: fx_connector_enabled | bool

- name: "Read Validator Secrets"
  shell: "cat {{ pia_path }}/validator_key_pair.pia"
  changed_when: false
  register: validator_key
  when: ilp_validator_enabled | bool

- name: "Read Fingerprints"
  shell: "cat {{ cert_path }}/{{ item.prefix }}.fpt"
  changed_when: false
  when: item.check
  with_items:
   - "{{ cert_items }}"
  register: fingerprints

#
# Configuration files
#

- name: "Construct Files Content"
  set_fact:
    client_credentials:
      operator:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'operator') | list }}"
        hashes: "{{ hashed_operator_passwords }}"
      monitor:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'monitor') | list }}"
        hashes: "{{ hashed_monitor_passwords }}"
      partner:
        users:  "{{ ripple_connect_partners | sum(attribute='partner_users', start=[]) | list }}"
        hashes: "{{ hashed_partner_passwords }}"
      custom_rate_operator:
        users:  "{{ ripple_connect_users | selectattr('type', 'equalto', 'custom_rate_operator') | list }}"
        hashes: "{{ hashed_custom_rate_operator_passwords }}"

- name: "Clean Examples"
  shell: "rm -f {{ ripple_solution_config_base }}/*example*"
  changed_when: false

- name: "Install Configuration Files"
  template:
    src:    "ripple-solution/{{ item }}.j2"
    dest:   "{{ ripple_solution_config_base }}/{{ item }}"
    mode:   '0644'
    force:  yes
    owner:  "{{ ripple_solution_user }}"
    group:  "{{ ripple_solution_group }}"
    seuser: system_u
    serole: object_r
    setype: usr_t
  # notify:
  #  - "Restart Ripple Solution"
  with_items:
   - config-ilp.json
   - config.json
   - database.json
   - entities.json
   - secrets.json
   - server.json
