---

- name: "Aggregate Data"
  set_fact:
    ripple_connect_info_tmp:
      name:           ripple_connect
      description:    Ripple Connect
      enabled:        "{{ ripple_connect_enabled | default(False) | bool }}"
      port:           "{{ ripple_connect_port }}"
      host:           "{{ ripple_connect_host }}"
      db_host:        "{{ ripple_connect_db_host }}"
      db_port:        "{{ ripple_connect_db_port }}"
      db_user:        "{{ ripple_connect_db_user }}"
      db_pass:        "{{ ripple_connect_db_pass }}"
      db_name:        "{{ ripple_connect_db_name }}"
      db_admin_user:  "{{ ripple_connect_db_admin_user }}"
      db_admin_pass:  "{{ ripple_connect_db_admin_pass }}"
      db_sql_file:    ripple-connect.sql
      db_check_table: public.db_schema_versions
      use_url:        "{{ ripple_connect_use_url | default('') }}"
      config:         "{{ ripple_connect_config }}"
      crt_prefix:     "{{ ripple_connect_crt_prefix }}"
      health_query:   ''
      health_json:    '"version": *"[0-9]+\.[0-9]+\.[0-9]+"'

    ilp_validator_info_tmp:
      name:           ilp_validator
      description:    ILP Validator
      enabled:        "{{ ilp_validator_enabled | default(False) | bool }}"
      port:           "{{ ilp_validator_port }}"
      host:           "{{ ilp_validator_host }}"
      db_host:        "{{ ilp_validator_db_host }}"
      db_port:        "{{ ilp_validator_db_port }}"
      db_user:        "{{ ilp_validator_db_user }}"
      db_pass:        "{{ ilp_validator_db_pass }}"
      db_name:        "{{ ilp_validator_db_name }}"
      db_admin_user:  "{{ ilp_validator_db_admin_user }}"
      db_admin_pass:  "{{ ilp_validator_db_admin_pass }}"
      db_sql_file:    validator.sql
      db_check_table: public.n_db_schema_versions
      use_url:        "{{ ilp_validator_use_url | default('') }}"
      config:         "{{ ilp_validator_config }}"
      crt_prefix:     "{{ validator_crt_prefix }}"
      health_query:   '/health'
      health_json:    '"status": *"OK"'

    fx_connector_info_tmp:
      name:           fx_connector
      description:    FX Connector
      enabled:        "{{ fx_connector_enabled | default(False) | bool }}"
      port:           "{{ fx_connector_port }}"
      host:           "{{ fx_connector_host }}"
      db_host:        "{{ fx_connector_db_host }}"
      db_port:        "{{ fx_connector_db_port }}"
      db_user:        "{{ fx_connector_db_user }}"
      db_pass:        "{{ fx_connector_db_pass }}"
      db_name:        "{{ fx_connector_db_name }}"
      db_admin_user:  "{{ fx_connector_db_admin_user }}"
      db_admin_pass:  "{{ fx_connector_db_admin_pass }}"
      db_sql_file:    connector.sql
      db_check_table: public.c_db_schema_versions
      use_url:        "{{ fx_connector_use_url | default('') }}"
      config:         "{{ fx_connector_config }}"
      crt_prefix:     "{{ fx_connector_crt_prefix }}"
      health_query:   '/health'
      health_json:    '"status": *"OK"'

    ilp_ledgers_extra_vars:
      name:           ilp_ledger
      description:    ILP Ledger
      db_sql_file:    ledger.sql
      db_check_table: public.l_db_schema_versions
      crt_prefix:     "{{ ledger_crt_prefix }}"
      health_query:   '/health'
      health_json:    '"status": *"OK"'

# NOTE: The various filter manipulate the various *_info_tmp dictionaries either
# by building new values or changing existing ones. Refer to the end results
# outputted and the end of this file or to the filters inside
# <role>/library/filters/ripple-solution.py for more information.

- name: "Build Temporary Datastructures"
  set_fact:
    ripple_connect_info: "{{ ripple_connect_info_tmp | build_ripple_extra(ripple_solution_db_dialect) }}"
    ilp_validator_info:  "{{ ilp_validator_info_tmp | build_ripple_extra(ripple_solution_db_dialect) }}"
    fx_connector_info:   "{{ fx_connector_info_tmp | build_ripple_extra(ripple_solution_db_dialect) }}"
    ilp_ledgers_info:    "{{ ilp_ledgers | map('build_ripple_extra', ripple_solution_db_dialect, ilp_ledgers_extra_vars) | list }}"

- name: "Build Final Datastructures"
  set_fact:
    ripple_connect_idx:   0
    ilp_validator_idx:    1
    fx_connector_idx:     2
    ilp_ledgers_base_idx: 3
    ilp_ledgers_count:    "{{ ilp_ledgers | length }}"
    ripple_solution_info: "{{ ([ripple_connect_info, ilp_validator_info, fx_connector_info] + ilp_ledgers_info) | list }}"
    ripple_solution_db_user_privileges:
     - type: schema
       priv: USAGE
       objs: public
     - schema: public
       type: table
       priv: SELECT,UPDATE,INSERT,DELETE
       objs: ALL_IN_SCHEMA
     - schema: public
       type: sequence
       priv: USAGE,SELECT
       objs: ALL_IN_SCHEMA

- name: "Crypto Paths"
  set_fact:
    cert_path: "{{ ripple_solution_cert_base }}/crt"
    key_path:  "{{ ripple_solution_cert_base }}/key"
    csr_path:  "{{ ripple_solution_cert_base }}/csr"
    pia_path:  "{{ ripple_solution_cert_base }}/pia"
    cert_ext_path: "{{ ripple_solution_cert_base }}/remotes"

- name: "Common Certificates Name"
  set_fact:
    ca_cert:    "{{ cert_path }}/{{ ripple_solution_ca_prefix }}.crt"
    ca_key:     "{{ key_path }}/{{ ripple_solution_ca_prefix }}.key"
    admin_cert: "{{ cert_path }}/{{ ripple_solution_admin_crt_prefix }}-crt.pem"
    admin_key:  "{{ key_path }}/{{ ripple_solution_admin_crt_prefix }}-key.pem"
    admin_crt_idx: "{{ ripple_solution_info | length }}"
    cert_items: "{{ (ripple_solution_info + [{'crt_prefix': ripple_solution_admin_crt_prefix, 'enabled': True}]) | list }}"

- name: "Ripple Solution Information"
  debug: var=ripple_solution_info
