---

- name: "Install Systemd Unit"
  copy:
    src:    etc/systemd/system/ripple-solution.service
    dest:   /etc/systemd/system/ripple-solution.service
    mode:   '0644'
    force:  yes
    owner:  root
    group:  root
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
  register: systemd_ripple

- name: "Update Systemd"
  command: systemctl daemon-reload
  when: systemd_ripple | changed

- name: "Start Ripple Solution"
  service: name=ripple-solution state=started enabled=yes
  register: ripple_solution_start

- name: "Restart Ripple Solution"
  service: name=ripple-solution state=restarted
  when:  ripple_solution_start | changed or
         config_files_status | changed or
         existing_certs_status | changed or
         created_certs_status | changed or
         ripple_solution_reset_db | default(False) | bool

- name: "Wait for all Services to Start"
  wait_for:
    timeout: 30
    host: "{{ item.host }}"
    port: "{{ item.port }}"
  when: item.enabled
  with_items:
   - "{{ ripple_solution_info }}"
