---

- name: "Install Client Certificate for Repository"
  copy:
    src:    "{{ item }}"
    dest:   "/var/lib/yum/{{ item | basename }}"
    mode:   '0400'
    force:  yes
    owner:  root
    group:  root
    seuser: system_u
    serole: object_r
    setype: rpm_var_lib_t
  with_items:
   - "{{ ripple_solution_repo_cert_files }}"

- name: "Setup Repository"
  yum_repository:
    name:          ripple-private
    description:   "Ripple Private Repo for Enterprise Linux $releasever - $basearchhttps://clients.ripple.com/repo/rpm/$releasever/$basearch"
    baseurl:       https://clients.ripple.com/repo/rpm/$releasever/$basearch
    enabled:       yes
    gpgcheck:      no
    sslclientcert: /var/lib/yum/ripple-private.client.crt
    sslclientkey:  /var/lib/yum/ripple-private.client.key
    sslverify:     yes

- name: "Install Packages"
  yum:
    update_cache: yes
    name: ripple-solution
    state: present

- name: "Copy Custom Scripts"
  copy:
    src:    opt/ripple-solution/scripts/decrypt_string.js
    dest:   /opt/ripple-solution/scripts/decrypt_string.js
    mode:   '0755'
    force:  yes
    owner:  "{{ ripple_solution_user }}"
    group:  "{{ ripple_solution_group }}"
    seuser: system_u
    serole: object_r
    setype: usr_t
