---
# tasks file for ripple-solution

- name: "Install Ripple Solution"
  include: install.yml
  tags: [ripple-solution, ripple-install]

- name: "Configure PostgreSQL"
  delegate_to: localhost
  include: postgres.yml
  tags: [ripple-solution, ripple-postgres]

- name: "Configure Databases"
  include: databases.yml
  tags: [ripple-solution, ripple-databases]

- name: "Create Certificates"
  include: certificates.yml
  tags: [ripple-solution, ripple-certificates]

- name: "Configure Ripple"
  include: config.yml
  tags: [ripple-solution, ripple-configuration]
