---

- name: "Remove User Privileges"
  postgresql_privs:
    login_host:      "{{ item.0.db_host }}"
    login_user:      "{{ item.0.db_admin_user }}"
    login_password:  "{{ item.0.db_admin_pass }}"
    port:            "{{ item.0.db_port }}"
    db:              "{{ item.0.db_name }}"
    role:            "{{ item.0.db_user }}"
    type:            "{{ item.1.type }}"
    schema:          "{{ item.1.schema | default(omit) }}"
    priv:            "{{ item.1.priv }}"
    objs:            "{{ item.1.objs }}"
    state:           absent
  ignore_errors: yes
  when: item.0.enabled | default(False) | bool and
        ripple_solution_reset_db | default(False) | bool
  with_nested:
   - "{{ ripple_solution_info }}"
   - "{{ ripple_solution_db_user_privileges }}"

- name: "Remove Users"
  postgresql_user:
    login_host: "{{ item.db_host }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_pass }}"
    port:       "{{ item.db_port }}"
    name:       "{{ item.db_user }}"
    db:         "{{ item.db_name }}"
    priv:       ALL
    state:      absent
  ignore_errors: yes
  when: item.enabled | default(False) | bool and
        ripple_solution_reset_db | default(False) | bool
  with_items:
   - "{{ ripple_solution_info }}"

- name: "Remove Databases"
  postgresql_db:
    login_host: "{{ item.db_host }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_pass }}"
    port:       "{{ item.db_port }}"
    name:       "{{ item.db_name }}"
    state:      absent
  ignore_errors: yes
  when: item.enabled | default(False) | bool and
        ripple_solution_reset_db | default(False) | bool
  with_items:
   - "{{ ripple_solution_info }}"


- name: "Create Databases"
  postgresql_db:
    login_host: "{{ item.db_host }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_pass }}"
    port:       "{{ item.db_port }}"
    name:       "{{ item.db_name }}"
    encoding:   UTF-8
    template:   template0
  when: item.enabled | default(False) | bool
  with_items:
   - "{{ ripple_solution_info }}"

- name: "Create Users"
  postgresql_user:
    login_host: "{{ item.db_host }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_pass }}"
    port:       "{{ item.db_port }}"
    name:       "{{ item.db_user }}"
    password:   "{{ item.db_pass }}"
    db:         "{{ item.db_name }}"
    priv:       ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    no_password_changes: yes
  when: item.enabled | default(False) | bool
  with_items:
   - "{{ ripple_solution_info }}"

- name: "Lock DB for Other Users"
  postgresql_privs:
    login_host: "{{ item.db_host }}"
    login_user: "{{ item.db_admin_user }}"
    login_password: "{{ item.db_admin_pass }}"
    port:       "{{ item.db_port }}"
    db:         "{{ item.db_name }}"
    role:       PUBLIC
    type:       database
    priv:       ALL
    state:      absent
  when: item.enabled | default(False) | bool
  with_items:
   - "{{ ripple_solution_info }}"
