---
# This file performs post-creation steps for the databases

- name: "Grant User Privileges - {{ component.description }}"
  postgresql_privs:
    login_host:      "{{ component.db_host }}"
    login_user:      "{{ component.db_admin_user }}"
    login_password:  "{{ component.db_admin_pass }}"
    port:            "{{ component.db_port }}"
    db:              "{{ component.db_name }}"
    role:            "{{ component.db_user }}"
    type:            "{{ item.type }}"
    schema:          "{{ item.schema | default(omit) }}"
    priv:            "{{ item.priv }}"
    objs:            "{{ item.objs }}"
  with_items:
   - "{{ ripple_solution_db_user_privileges }}"
